name: phylogeny_analysis
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - biopython
  - jupyterlab
  - pandas
  - seaborn
  - snakemake
  - mafft
  - iqtree
  - ete3
  - emboss
  - cd-hit
  - dna_features_viewer
  - pymsaviz
  - hyphy