name: lasv_dms_library_design_env
channels:
  - bioconda
  - conda-forge
  - defaults

dependencies:
    - python=3.8.10
    - pip=21.2.2
    - pandas=1.3.1
    - plotnine=0.8.0
    - mafft=7.487
    - jupyter=1.0.0
    - jupyterlab=3.1.2
    - jupyter_contrib_nbextensions=0.5.1
    - biopython=1.79
    - iqtree=2.1.4_beta
    - runipy=0.1.5
    - altair=4.1.0
    - snakemake=6.2.1
    - git-lfs=2.13.3
    - minimap2=2.18
    - pbccs=6.0.0
    - sra-tools=2.10.9
    - umi_tools=1.1.2
    - pip:
        - alignparse==0.2.6
        - dms-variants==0.8.10
        - neutcurve==0.5.7
        - logomaker==0.8
        - phydms==2.4.1