# ======================================================== #
#                                                          #
#     Edit the information in this configuration file      #
#                                                          #
# ======================================================== #

# ====== Info applying to the whole variant library ====== #
organism: Mammarenavirus lassaense
strain: Josiah
isolation_source: HEK-293T-rtTA
collection_date: 2022/2023
geographic_location: 'USA: Washington'
sample_type: plasmid

# ======== Info for Illumina barcodes BioSamples ======== #
barcode_runs: 
  
  # Path to the barcoded runs csv file that will go into the BioSample
  file_path: ../data/barcode_runs.csv
  
  # Edit this data that goes into the SRA metadata table for the BioSample
  accession: SAMN39709215
  sample_id_columns: [sample, library, date]
  title_prefix: LASV GPC Josiah Illumina barcode sequencing for sample  
  description: Illumina barcode sequencing for LASV GPC Josiah
  strategy: AMPLICON
  source: SYNTHETIC
  selection: PCR
  layout: single
  platform: ILLUMINA
  model: NextSeq 2000

  # Meaningful BioSample specific folder name for FTP upload
  ftp_subfolder: LASV_Josiah_GP_DMS_Illumina_barcodes


# ========== Info for PacBio library BioSample ========== #
pacbio_runs:
  
  # Path to the pacbio runs that will be included in the BioSample
  file_path: ../data/PacBio_runs.csv
 
  # This data goes into the SRA metadata table
  accession: SAMN39732267
  title_prefix: PacBio CCSs linking variants to barcodes for LASV GPC Josiah deep mutational scanning for
  description: PacBio CCSs of barcoded LASV GPC Josiah variants
  strategy: Synthetic-Long-Read
  source: SYNTHETIC
  selection: PCR
  layout: single
  platform: PACBIO_SMRT
  model: Sequel IIe

  # Meaningful BioSample specific folder name for FTP upload
  ftp_subfolder: LASV_Josiah_GP_DMS_PacBio_CCSs

# =========== Info for uploading to SRA via FTP =========== #
# These come from the SRA FTP upload instructions.
ftp_username: subftp
ftp_account_folder: uploads/ccarr3_uw.edu_mHlOEHCt

  